on:
  push:
    branches:
      - develop

permissions:
  contents: write
  actions: write

# There should only be one instance of this
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Deploy snapshot builds
jobs:
  deploy-release-snapshot:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Setup build environment
      uses: agrahn/android-password-store/.github/reusable-workflows/setup-gradle@develop
      with:
        fetch-depth: 0
        dependency-graph: generate-and-submit

    - name: Decrypt secrets
      shell: bash
      run: scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Build release app
      shell: bash
      run: ./gradlew collectFreeReleaseApks bundleFreeRelease
      env:
        SNAPSHOT: "true"

    - name: Clean secrets
      shell: bash
      run: scripts/signing-cleanup.sh

    - name: Deploy snapshot
      shell: bash
      run: scripts/deploy-snapshot.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
