name: Update Publix Suffix List data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-publicsuffix-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: agrahn/android-password-store/.github/reusable-workflows/setup-gradle@develop

      - name: Download new publicsuffix data
        shell: bash
        run: ./gradlew updatePSL

      - name: Check if PR is required
        shell: bash
        run: if [[ $(git status -s) != '' ]]; then echo "UPDATED=true" >> $GITHUB_ENV; fi

      - name: Verify update publicsuffixes file
        if: "${{ env.UPDATED == 'true' }}"
        shell: bash
        run: ./gradlew :autofill-parser:test -PslimTests

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        if: "${{ env.UPDATED == 'true' }}"
        with:
          author: GitHub Actions <noreply@github.com>
          base: develop
          body: This is an automated pull request to update the publicsuffixes file to the latest copy from Mozilla
          branch: bot/update-psl
          commit-message: "autofill-parser: update publicsuffixes file"
          labels: A-PSL, S-automerge
          title: Update Public Suffix List data
          token: ${{ secrets.PSL_UPDATE_TOKEN }}

      - name: Enable automerge for PR
        if: "${{ steps.cpr.outputs.pull-request-operation == 'created' }}"
        shell: bash
        run: |
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
